:: Generated by: https://github.com/swagger-api/swagger-codegen.git
::

@echo off

dotnet restore src\Calculator
dotnet build src\Calculator
echo Now, run the following to start the project: dotnet run -p src\Calculator\Calculator.csproj --launch-profile web.
echo.
