/*
 * Math Operations API
 *
 * A REST API that performs a math operation on two numeric values based on an operation type provided in the HTTP header. Requires JWT authentication.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using Calculator.Models;

namespace Calculator.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public interface IMathController
    {
        /// <summary>
        /// Perform a math operation on two numbers
        /// </summary>

        /// <param name="request"></param>
        /// <param name="operation">The type of operation to perform (add, subtract, multiply, divide)</param>
        /// <response code="200">Successful result of the math operation</response>
        /// <response code="400">Bad request (e.g., unsupported operation or division by zero)</response>
        /// <response code="401">Unauthorized (missing or invalid JWT)</response>
        IActionResult Calculate([FromBody]MathRequest request, [FromHeader][Required()]string operation);
    }
}
